# Site settings
title: Test Rich Results
email: scotmarvin@gmail.com
description: Trying out SEO returns in Google page.
baseurl: "/paradocs"
# permalink: pretty
defaults:
  -
    scope:
      path: "" # Apply to all files
    values:
      layout: "default"

# Build settings
markdown: kramdown
highlighter: rouge
theme: jekyll-theme-minimal

plugins:
  - jekyll-feed

kramdown:
    toc_levels: 1..3

# Exclude
exclude: ['node_modules', 'vendor']
